In [3]:
# Import numpy
import numpy as np
from time import process_time

### List vs Numpy Array Time Taken 

In [4]:
# Time Taken by list
python_list  = [ i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time-start_time)  

0.0


In [5]:
np_arr = np.array([i for i in range(10000)])
start_time = process_time()
print(start_time)

np_arr = np_arr + 5
end_time = process_time()
print(end_time)
print(end_time-start_time)  

4.453125
4.453125
0.0


In [6]:
# 1D arrays
a = np.array([1, 2, 3, 4, 5])
print(a)
type(a)
a.shape

[1 2 3 4 5]


(5,)

In [7]:
# 2D arrays
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)
type(b)
b.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [8]:
# data type manipulation of array

c = np.array([1, 2, 3, 4, 5], dtype='float32')
print(c)
type(c)

[1. 2. 3. 4. 5.]


numpy.ndarray

In [9]:
# creating a numpy array with zeros 
d = np.zeros((3,3))     # (3,) represents no of rows (,3) represents no of columns
d

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
# creating a numpy array with ones
e = np.ones((4,5)) 
e

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
# array of perticular value
f = np.full((4,3), 10)
f

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [12]:
# creating identity matrix (In identity matrix no of rows and columns are same or equal to each other)
a = np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
# creating array with random values
b = np.random.random((4,4))
b

array([[0.46843872, 0.73312424, 0.39770218, 0.45449249],
       [0.69304713, 0.40439119, 0.41522126, 0.83324332],
       [0.41764545, 0.83741393, 0.18200182, 0.91892662],
       [0.8109092 , 0.42564738, 0.75046359, 0.80477335]])

In [14]:
# creating array with random integer values with specific range
c = np.random.randint(1,100,(4,4))
#randint -> random integer values (start_value, end_value, shape of the array)
c

array([[ 5, 68, 70, 31],
       [19, 93, 46, 88],
       [98, 55, 10,  5],
       [87, 36,  3, 86]], dtype=int32)

In [15]:
# creating array with evenly spaced values
d = np.linspace(10, 20, 5)
# linspace => Linear spacing of numbers over a specified interval.(start, stop, number of elements)
print(d)

[10.  12.5 15.  17.5 20. ]


In [16]:
# creating array with step values
a = np.arange(10, 40, 5)
print(a)

[10 15 20 25 30 35]


In [17]:
# converting list to numpy array

python_list = [1, 2, 50, 60, 70]
numpy_array = np.asarray(python_list)
print(numpy_array)
type(numpy_array)

[ 1  2 50 60 70]


numpy.ndarray

### Mathematical Operations on array

In [18]:
list_1 = [1, 2, 3, 4, 5]
list_2 = [6, 7, 8, 9, 10]

print(list_1 + list_2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [19]:
a = np.random.randint(0, 10, (3, 4))
b = np.random.randint(10, 20,(3, 4))

In [21]:
print(a)
print()
print(b)

[[5 2 7 4]
 [1 2 3 9]
 [6 0 5 9]]

[[17 11 13 10]
 [18 18 18 19]
 [19 15 12 12]]


In [26]:
print((a + b))
print((a - b))
print((a * b))
print((a / b))

[[22 13 20 14]
 [19 20 21 28]
 [25 15 17 21]]
[[-12  -9  -6  -6]
 [-17 -16 -15 -10]
 [-13 -15  -7  -3]]
[[ 85  22  91  40]
 [ 18  36  54 171]
 [114   0  60 108]]
[[0.29411765 0.18181818 0.53846154 0.4       ]
 [0.05555556 0.11111111 0.16666667 0.47368421]
 [0.31578947 0.         0.41666667 0.75      ]]


In [27]:
print( np.add(a, b))
print( np.subtract(a, b))
print(np.multiply(a, b))
print(np.divide(a, b))

[[22 13 20 14]
 [19 20 21 28]
 [25 15 17 21]]
[[-12  -9  -6  -6]
 [-17 -16 -15 -10]
 [-13 -15  -7  -3]]
[[ 85  22  91  40]
 [ 18  36  54 171]
 [114   0  60 108]]
[[0.29411765 0.18181818 0.53846154 0.4       ]
 [0.05555556 0.11111111 0.16666667 0.47368421]
 [0.31578947 0.         0.41666667 0.75      ]]


### Array Manipulation


In [28]:
arr = np.random.randint(1, 10, (3, 2))
print(arr)
print(arr.shape)

[[4 8]
 [5 5]
 [7 1]]
(3, 2)


In [30]:
# transpose -> Convert rows into columns and vice versa
trans = np.transpose(arr)
print(trans)
print(trans.shape)

[[4 5 7]
 [8 5 1]]
(2, 3)


In [31]:
trans2 = arr.T
print(trans2)
print(trans2.shape)

[[4 5 7]
 [8 5 1]]
(2, 3)


### Reshaping the array

In [32]:
arr2 = np.random.randint(0, 10, (2, 3))
print(arr2)
print(arr2.shape)

[[2 4 7]
 [9 3 9]]
(2, 3)


In [35]:
arr3 = arr2.reshape(3, 2)
print(arr3)
print(arr3.shape)

[[2 4]
 [7 9]
 [3 9]]
(3, 2)
